### ISSUE TITLE
Falsche Zuordnung der Trennelemente im Backend

### ISSUE THREAD

**Issue by mj1985** [contao-bootstrap/carousel#1]
Moin,
wenn ich im Backend bereits ein Carousel angelegt habe und dann bei einem zweiten (in dem gleichen Artikel) die Trennelemente erstelle, dann werden die Trennelemente beim ersten Carousel nach dem `Carousel Start` angezeigt. Das ist etwas verwirrend.

Update: Egal was ich mache, die Trennelemente werden immer dem ersten Carousel zugeordnet.
Einzige Möglichkeit, ein Trennelement kopieren/duplizieren und dann über "Fix now" neu zuordnen

**Comment by dmolineus** [comment]
The recent changes in the contao-bootstrap/core#develop should fix it. Please test it.

**Comment by dmolineus** [comment]
Closed.
