### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by CodeAlDente** [contao-bootstrap/carousel#2]
I would like to see the option to set background images just like here:
http://ironsummitmedia.github.io/startbootstrap-modern-business/index.html

Do you think this is possible? :smile:

**Comment by dmolineus** [comment]
It could already be done by assigning custom css classes and set the backround images using css. Not sure if I will add it as this is not default Bootstrap feature.

**Comment by CodeAlDente** [comment]
Alright, thanks for the heads up! :+1:
