### ISSUE TITLE
Mehrere Carousels in einem Artikel - gleiche IDs werden vergeben

### ISSUE THREAD

**Issue by mj1985** [contao-bootstrap/carousel#3]
Durch die Verwendung von time() - erhalten alle Carousels auf der Seite die gleiche ID, besser wäre es die Element-ID zu verwenden:

```
$this->id
```

Konkret im Template gallery_carousel_34.html5 (Zeile 1):

```
<?php if($this->cssID[0] == '') : $cssId = 'carousel_' . $this->id; else: $cssId = 'carousel_' . $this->cssID[0]; endif; ?>
```

**Comment by dmolineus** [comment]
This template is part of contao-bootstrap/templates. I copied the ticket to it.
